export const THROW_ERROR = 'THROW_ERROR';

// WAREHOUSE
export const FETCH_WAREHOUSES = 'FETCH_WAREHOUSES';
export const FETCH_WAREHOUSE = 'FETCH_WAREHOUSE';
export const SEARCH_WAREHOUSE = 'SEARCH_WAREHOUSE';

// SKU
export const FETCH_WAREHOUSE_SKU = 'FETCH_WAREHOUSE_SKU';
export const FETCH_WAREHOUSE_SKUS = 'FETCH_WAREHOUSE_SKUS';
export const SEARCH_SKU = 'SEARCH_SKU';

// PICKLIST
export const FETCH_FACILITIES_AND_AMENITIES = 'FETCH_FACILITIES_AND_AMENITIES';
export const FETCH_BUILDING_TYPES = 'FETCH_BUILDING_TYPES';
export const FETCH_TRUCK_TYPES = 'FETCH_TRUCK_TYPES';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';

// DELIVERY NOTICE
export const FETCH_DELIVERY_NOTICE = 'FETCH_DELIVERY_NOTICE';
export const FETCH_DELIVERY_NOTICES = 'FETCH_DELIVERY_NOTICES';
export const SEARCH_DELIVERY_NOTICE = 'SEARCH_DELIVERY_NOTICE';
export const FETCH_DELIVERY_NOTICE_SKU = 'FETCH_DELIVERY_NOTICE_SKU';
export const SEARCH_DELIVERY_NOTICE_SKU = 'SEARCH_DELIVERY_NOTICE_SKU';

// AUTH
export const FETCH_ACCOUNT_DETAILS = 'FETCH_ACCOUNT_DETAILS';

// LOGS
export const FETCH_WAREHOUSE_LOGS = 'FETCH_WAREHOUSE_LOGS';
export const FILTER_LOGS = 'FILTER_LOGS';

//RECEIVING AND RELEASING
export const FETCH_RECEIVING_RELEASING = 'FETCH_RECEIVING_RELEASING';
export const SEARCH_RECEIVING_RELEASING = 'SEARCH_RECEIVING_RELEASING';
