export const THROW_ERROR = 'THROW_ERROR';

// WAREHOUSE
export const FETCH_WAREHOUSES = 'FETCH_WAREHOUSES';
export const FETCH_WAREHOUSE = 'FETCH_WAREHOUSE';

// PICKLIST
export const FETCH_FACILITIES_AND_AMENITIES = 'FETCH_FACILITIES_AND_AMENITIES';